### ISSUE TITLE
LIFX Plug-in Error

### ISSUE THREAD

**Issue by the-fezzo** [marcushultman/eventghost-lifx#4]
I've been getting this error message while running any instance of a LIFX action in EventGhost. This seems to have happened suddenly in the last couple of days without any changes to hardware/software on my end:

    Error in Action: "LIFX: Set State: group:Desk"
      Traceback (most recent call last) (1722):
        File "C:\Program Files (x86)\EventGhost\eg\Classes\ActionBase.py", line 170, in CallWrapper
          return self(*args)
        File "C:\Program Files (x86)\EventGhost\plugins\LIFX\__init__.py", line 79, in __call__
          return super(SelectorLifxAction, self).__call__(*data)
        File "C:\Program Files (x86)\EventGhost\plugins\LIFX\__init__.py", line 70, in __call__
          return self.action(url, headers=self.plugin.auth, data=payload)
        File "C:\Program Files (x86)\EventGhost\plugins\LIFX\__init__.py", line 59, in action
          LifxAction.GET](url, *args, **kwargs).json()
        File "C:\Program Files (x86)\EventGhost\lib26\site-packages\requests\api.py", line 99, in put
          return request('put', url, data=data, **kwargs)
        File "C:\Program Files (x86)\EventGhost\lib26\site-packages\requests\api.py", line 44, in request
          return session.request(method=method, url=url, **kwargs)
        File "C:\Program Files (x86)\EventGhost\lib26\site-packages\requests\sessions.py", line 456, in request
          resp = self.send(prep, **send_kwargs)
        File "C:\Program Files (x86)\EventGhost\lib26\site-packages\requests\sessions.py", line 559, in send
          r = adapter.send(request, **kwargs)
        File "C:\Program Files (x86)\EventGhost\lib26\site-packages\requests\adapters.py", line 382, in send
          raise SSLError(e, request=request)
      SSLError: [Errno 1] _ssl.c:493: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Things I've tried (unsuccessfully) are:

- Generating a new LIFX token and replacing that in the plug-in
- Updating firmware on LIFX lights
- Making a new LIFX event tree from scratch
- Trying pre-release version of EventGhost (0.5 RC6), error message is slightly different but mostly the same

Many thanks in advance for any help provided. Cheers :)

**Comment by 4r7** [comment]
@the-fezzo I have come across the same issue. Whilst I'm not 100% sure of the cause (maybe something wrong with the LIFX API root certificate?) there is a quick solution, although generally this is not recommended as it will disable SSL Certificate Verification for all calls to the LIFX HTTP API. 

So use at your own risk, however I don't personally consider this particular situation a risky one for disabling the certificate verification.

To solve it, I have simply inserted the following line of code before line 54 in the __init__.py file:

`kwargs["verify"] = False`

The resulting action function in the file should look like this:
![lifxAction](https://user-images.githubusercontent.com/49716021/147994751-096c124c-f4f5-41d4-b42b-a7cc9fd7ee39.png)

If I get time I will look in to the cause of the issue further to see if there is a proper solution (still not sure if its LIFX's API server problem).

Hope that helps!

**Comment by the-fezzo** [comment]
> To solve it, I have simply inserted the following line of code before line 54 in the **init**.py file:

Great, thanks so much. After months of not working, this did the trick.

After my original post, I did some more digging, and it turns out a few other EventGhost plugins suddenly stopped working on September 30, 2021 -- coinciding with the exact expiry date of the DST Root CA X3 Certificate that EventGhost apparently uses for verification.

I tried many solutions to fix it ([one of which is here](https://www.stephenwagner.com/2021/09/30/sophos-dst-root-ca-x3-expiration-problems-fix/)) to no avail, could give it a try though to see if it works for you.
